### ISSUE TITLE
Neither vpm or vpkg build at the moment

### ISSUE THREAD

**Issue by 0b1kn00b** [vlang/awesome-v#101]
I downloaded the git  release, there's syntax errors with both package managers.

**Comment by thebigsmileXD** [comment]
I don't think this is related to this repository, which is only collecting packages in a README. You should head to the respecting repositories and report there.

**Comment by 0b1kn00b** [comment]
While that's technically true, the fact that neither of the package managers of a language compile with a release should set *someone's* hair on fire, and it does say this is a curated list.

**Comment by Terisback** [comment]
Many language changes have taken place since then. I don't know about vpkg, but vpm now expects a big [PR](https://github.com/vlang/vpm/pull/16) with a design update and all the necessary fixes for the current version of the language.
When the language reaches a stable stage, we can think about removing some non-compilable repositories from the list.
Anyway, this issue does not related to this repository, open issue in the corresponding repositories.

**Comment by medvednikov** [comment]
i've removed vpkg since it doesn't compile, is no longer maintained, and official vpm fits the one way policy

**Comment by JalonSolov** [comment]
While true, removing something that is no longer maintained is still a good idea.
